/// <auto-generated>
/// This file has been automatically generated. Do not modify.
/// </auto-generated>
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable RedundantAssignment
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace

using System;
using RegressionGames;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace RGThirdPersonDemo
{
    public class RGStateEntity_PlayerAttack : RGStateEntityBase
    {
        public static readonly Type BehaviourType = typeof(PlayerAttack);
        public static readonly string EntityTypeName = "PlayerAttack";
        public static readonly bool IsPlayer = true;
        public override string GetEntityType()
        {
            return EntityTypeName;
        }

        public override bool GetIsPlayer()
        {
            return IsPlayer;
        }

        public override void PopulateFromMonoBehaviour(MonoBehaviour monoBehaviour)
        {
            var behaviour = (PlayerAttack)monoBehaviour;
            this["IsAttacking"] = behaviour.IsAttacking();
        }

        public bool IsAttacking => (bool)this["IsAttacking"];
    }
}