using System;
using RegressionGames.StateActionTypes;
using UnityEngine;

// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
namespace RegressionGames.TEST_REMOVE
{
    
    /*
     * WARNING: This class is autogenerated and CANNOT be modified.
     * Any attempt to change this class will trigger it to be autogenerated again.
     */
    public class RgStateEntity_BehaviourName : RGStateEntityBase
    {
        public static readonly Type BehaviourType = typeof(BehaviourName);

        public static readonly string EntityTypeName = "BehaviourNameTypeTest";

        public static readonly bool IsPlayer = true;
        public override bool GetIsPlayer()
        {
            return IsPlayer;
        }

        public override string GetEntityType()
        {
            return EntityTypeName;
        }

        public override void PopulateFromMonoBehaviour(MonoBehaviour monoBehaviour)
        {
            var behaviour = (BehaviourName)monoBehaviour;
            this["spatialOrientation"] = behaviour.SpatialOrientation;
            this["spatialRotation"] = behaviour.SpatialRotation;
            this["spatialBounds"] = behaviour.SpatialBounds;
            this["spatialSize"] = behaviour.SpatialSize();
        }
        
        public Vector3 spatialOrientation => (Vector3)this["spatialOrientation"];
    }
}
