name: Unity Build and Test

on:
  # Build every commit to 'main'
  push:
    branches:
      - main

  # Build every PR
  pull_request:

jobs:
  test:
    name: Unity Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Retrieve Cached Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: src/RGUnityBots
          githubToken: ${{ secrets.GITHUB_TOKEN }}